name: Spark Scala Test Transformations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK 8 instead of JDK 11
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'sbt'

      # Run the build and tests using sbt
      - name: Run Tests
        run: sbt clean test

      # Upload test results (Optional for better reporting)
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/test-reports/

      # Upload dependency graph for Dependabot (Optional)
      - name: Upload Dependency Graph
        uses: scalacenter/sbt-dependency-submission@v2
